### ISSUE TITLE
Error: Cannot find module 'mongodb/node_modules/bson'

### ISSUE THREAD

**Issue by dsinkey** [scotch-io/react-tweets#22]
I got this error when starting mongodb.  Here's a link to resolve the problem.

https://github.com/Automattic/mongoose/issues/2718

I changed to mongoose 4.2.6 in package.json and ran this.  Deletes the node_modules and re-installs them.

npm install -g node-gyp 
cd /to/you/project
rm -rf node_modules
npm install

**Comment by gavmck** [comment]
Updating mongoose has fixed this for me

**Comment by npineda** [comment]
I second gavmck's statement

**Comment by whupanglong** [comment]
I fixed it with dsinkey's solution ,thanks

**Comment by jblossomweb** [comment]
I attempted to be a good citizen and send a PR for the dep change in package.json
Then I realized I do not have permission to push a branch. So here would be the diff:

`
--- a/package.json
+++ b/package.json
@@ -14,7 +14,7 @@
   "dependencies": {
     "express": "~4.9.7",
     "express-handlebars": "~1.1.0",
-    "mongoose": "^3.8.23",
+    "mongoose": "^4.2.6",
`

**Comment by sevilayha** [comment]
Updated the mongoose version in `package.json`. Thanks everyone.

**Comment by noisytoken** [comment]
I am still getting the same error, even after executing the following commands.

```
npm install -g node-gyp
cd /to/you/project
rm -rf node_modules
npm install
```
Which version of node are you guys using ? mine is 8.1 and I am on Windows.

**Comment by rosselpha** [comment]
me too how did you fixed it

**Comment by cayrescript** [comment]
@jblossomweb Thanks man, works for me!

**Comment by Charlie91** [comment]
"npm update mongoose" - doesn't work for me, but when i did 
"npm r mongoose"
and then
"npm i mongoose"
everything was fine
